### ISSUE TITLE
example.yml config throwing error

### ISSUE THREAD

**Issue by alice-carr** [shoreditch-ops/artillery-engine-kinesis#3]
Hi, when running the [example.yml](https://github.com/artilleryio/artillery-engine-kinesis/blob/master/example.yml) I'm running into the following error:

```
.   /usr/local/lib/node_modules/artillery/core/lib/engine_util.js:77
    if (typeof opts.overValues !== 'undefined') {
                    ^

TypeError: Cannot read property 'overValues' of undefined
    at aLoop (/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:77:21)
    at fn (/usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)
```

Artillery version is 1.6.0-28 and I'm running with `artillery run example.yml`.
Could you advise if this is a bug/ issue with example.yml or I'm doing something wrong?
Note: I'm also seeing this issue whenever trying to run a loop with artillery-engine-kinesis

**Comment by rabindragogoi** [comment]
.   /usr/local/lib/node_modules/artillery/core/lib/engine_util.js:77
    if (typeof opts.overValues !== 'undefined') {
                    ^

TypeError: Cannot read property 'overValues' of undefined
    at aLoop (/usr/local/lib/node_modules/artillery/core/lib/engine_util.js:77:21)
    at fn (/usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:1206:34)
    at runCallback (timers.js:705:18)
    at tryOnImmediate (timers.js:676:5)
    at processImmediate (timers.js:658:5)

**Comment by rabindragogoi** [comment]
Can you please help me out here what is the issue?

**Comment by rabindragogoi** [comment]
Alice : Did you found the solution? I am too facing the same issue

**Comment by alice-carr** [comment]
@rabindragogoi it seems to be the [loop causing the issues](https://github.com/artilleryio/artillery-engine-kinesis/blob/master/example.yml#L18) - if you remove this line it works - just means you can't loop with artillery-engine-kinesis which is a shame

**Comment by hassy** [comment]
#7 possibly fixes this?
