### ISSUE TITLE
not able to use it in 

### ISSUE THREAD

**Issue by rabindragogoi** [shoreditch-ops/artillery-engine-kinesis#4]
I installed 
- artillery as : npm install -g artillery
- artillery engine as : npm install -g artillery-engine-kinesis

but while I am running the test.yaml script in my ec2 instance:
It is returning the below error : 
===================================
Started phase 0, duration: 1s @ 10:21:42(+0000) 2020-02-27
..  /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/core/lib/engine_http.js:175
    if (!params.url && !params.uri) {
                ^

TypeError: Cannot read property 'url' of undefined
    at f (/home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/core/lib/engine_http.js:175:17)
    at fn (/home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
    at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
    at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
    at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
    at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:1206:34)

====================================

my test.yaml file is :

config:
  target: "test_kenisis"
  kinesis:
    region: "us-east-2"
  phases:
   - arrivalCount: 5
     duration: 1
  engines:
    kinesis: {} 
scenarios:
  - name: "Push to stream"
    flow:
      - loop:
        - putRecord:
            data:
            name: "test_1"
            location: "London, UK"
        - think: 1
        count: 60

**Comment by rabindragogoi** [comment]
> I installed
> 
> * artillery as : npm install -g artillery
> * artillery engine as : npm install -g artillery-engine-kinesis
> 
> # but while I am running the test.yaml script in my ec2 instance:
> It is returning the below error :
> Started phase 0, duration: 1s @ 10:21:42(+0000) 2020-02-27
> .. /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/core/lib/engine_http.js:175
> if (!params.url && !params.uri) {
> ^
> 
> TypeError: Cannot read property 'url' of undefined
> at f (/home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/core/lib/engine_http.js:175:17)
> at fn (/home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:746:34)
> at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:1213:16
> at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:166:37
> at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:706:43
> at /home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:167:37
> at Immediate. (/home/ec2-user/.nvm/versions/node/v13.9.0/lib/node_modules/artillery/node_modules/async/lib/async.js:1206:34)
> 
> ====================================
> 
> my test.yaml file is :
> 
> config:
> target: "test_kenisis"
> kinesis:
> region: "us-east-2"
> 
> # Emulate 10 publishers
> phases:
> 
> * arrivalCount: 5
>   duration: 1
>   engines:
>   kinesis: {}
> 
> scenarios:
> 
> * name: "Push to stream"
>   flow:
>   
>   * loop:
>     
>     * putRecord:
>       # data may be a string or an object. Objects
>       # will be JSON.stringified.
>       data:
>       name: "test_1"
>       location: "London, UK"
>     * think: 1
>       count: 60
