### ISSUE TITLE
Running kinesis-artillery-plugin on 12.16.1 fails with the following error

### ISSUE THREAD

**Issue by rajeshkp** [shoreditch-ops/artillery-engine-kinesis#5]
Running kinesis-artillery-plugin on 12.16.1 fails with the following error

```
.   TypeError: Cannot create property 'mode' on number '10'
    at /Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/core/lib/runner.js:67:20
    at /Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/node_modules/lodash/lodash.js:4925:15
    at baseForOwn (/Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/node_modules/lodash/lodash.js:2990:24)
    at /Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/node_modules/lodash/lodash.js:4894:18
    at Function.forEach (/Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/node_modules/lodash/lodash.js:9368:14)
    at runner (/Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/core/lib/runner.js:66:5)
    at Runner.run (/Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/lib/runner-sp.js:60:3)
    at done (/Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/lib/commands/run.js:191:14)
    at /Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/node_modules/async/lib/async.js:52:16
    at Immediate.<anonymous> (/Users/rajesh/.nvm/versions/node/v12.16.1/lib/node_modules/artillery/node_modules/async/lib/async.js:1206:34)

```

**Comment by hassy** [comment]
hard to tell what's going wrong without seeing at least some of the test script
