### ISSUE TITLE
Cannot read properties of undefined (reading 'processor')

### ISSUE THREAD

**Issue by shroman** [shoreditch-ops/artillery-engine-kinesis#6]
kinesis engine doesn't seem to be able to use `processor` function.
```
worker error, id: 1 TypeError [Error]: Cannot read properties of undefined (reading 'processor')
    at /usr/local/lib/node_modules/artillery-engine-kinesis/index.js:45:30
    at fn (/usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:746:34)
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:1213:16
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:166:37
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:706:43
    at /usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:167:37
    at Immediate.<anonymous> (/usr/local/lib/node_modules/artillery-engine-kinesis/node_modules/async/lib/async.js:1206:34)
```

**Comment by ravelantunes** [comment]
@shroman I was having the same issue, and I believe this PR should solve it: https://github.com/artilleryio/artillery-engine-kinesis/pull/7
